version: '3.8'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPass@123"
    networks:
      - pos-network

  pos-api:
    build: .
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=PosDb;User Id=sa;Password=StrongPass@123;TrustServerCertificate=True;"
    networks:
      - pos-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - pos-api
    networks:
      - pos-network

networks:
  pos-network:
